In [121]:
import scipy.linalg as la

In [142]:
A = np.array([[0.6289,0.6002,0.6861,0.5],[0.1258,0.12,0.0858,0.2143],[0.1572,0.2401,0.1715,0.2143],\
              [0.0898,0.04,0.0572,0.0714]])
A

array([[0.6289, 0.6002, 0.6861, 0.5   ],
       [0.1258, 0.12  , 0.0858, 0.2143],
       [0.1572, 0.2401, 0.1715, 0.2143],
       [0.0898, 0.04  , 0.0572, 0.0714]])

In [143]:
results = la.eig(A)

eigvals, eigvecs = la.eig(A)

In [139]:
print("Eignvalues", eigvals)
print("Eigenvectors", eigvecs)

Eignvalues [1.49811822+0.j         0.48866721+0.j         0.00250728+0.06228865j
 0.00250728-0.06228865j]
Eigenvectors [[ 0.9004123 +0.j          0.86661447+0.j          0.72564491+0.j
   0.72564491-0.j        ]
 [ 0.3848505 +0.j         -0.29027806+0.j         -0.01070728+0.05484354j
  -0.01070728-0.05484354j]
 [ 0.18846722+0.j          0.34935346+0.j         -0.50289806+0.20989128j
  -0.50289806-0.20989128j]
 [ 0.07501928+0.j          0.20656757+0.j         -0.18473308-0.37313521j
  -0.18473308+0.37313521j]]


In [140]:
#use real to convert the array of eigenvalues to real numbers
eigvals = eigvals.real
print(eigvals)

[1.49811822 0.48866721 0.00250728 0.00250728]


In [154]:
eigvecs=eigvecs.real
eigvecs

array([[ 0.93965101,  0.68574745,  0.68574745, -0.52467803],
       [ 0.18760708, -0.44340124, -0.44340124, -0.44895929],
       [ 0.26200826, -0.22541822, -0.22541822,  0.64293606],
       [ 0.11494017, -0.01779816, -0.01779816,  0.33133328]])

In [158]:
s1=0
s2=0
s3=0
s4=0
for i in range(len(eigvecs)):
    s1+=(abs(eigvecs[i,0]))
    s2+=(abs(eigvecs[i,1]))
    s3+=(abs(eigvecs[i,2]))
    s4+=(abs(eigvecs[i,3]))
    
print("Price or Cost",s1/4)
print("Storage Space",s2/4)
print("Camera Quality",s3/4)
print("Looks",s4/4)

Price or Cost 0.37605162856630686
Storage Space 0.3430912663351578
Camera Quality 0.3430912663351578
Looks 0.486976665370799


In [160]:
#check
v1 = eigvecs[:,0] # First column is the first eigenvector
print(v1)
v2 = eigvecs[:,1] # Second column is the second eigenvector
print(v2)

[0.93965101 0.18760708 0.26200826 0.11494017]
[ 0.68574745 -0.44340124 -0.22541822 -0.01779816]


In [161]:
#IF the dot product of eigenvectors and is zero 
#The number above is very close to zero and is due to rounding errors in the computations) and so they are orthogonal!

v1 @ v2

0.5000709153543893

In [162]:
#a perfect orthogonal demo
n = 4
P = np.random.randint(0,10,(n,n))
print(P)

[[0 9 0 4]
 [2 7 1 2]
 [0 7 5 9]
 [4 4 9 1]]


In [163]:
#Create the symmetric matrix
#S=P(transposed)P
S = P @ P.T
print(S)

[[ 97  71  99  40]
 [ 71  58  72  47]
 [ 99  72 155  82]
 [ 40  47  82 114]]


In [165]:
evals, evecs = la.eig(S)
evals = evals.real
print(evals)

[324.01285325  71.91506887   0.5847747   27.48730318]


In [166]:
#eigenvectors
print(evecs)

[[ 0.48283202  0.49806227  0.62878193  0.35134101]
 [ 0.38335666  0.16993632 -0.73030627  0.53926994]
 [ 0.65679433  0.09341287 -0.17134256 -0.72837969]
 [ 0.43420285 -0.84518026  0.2047627   0.23496906]]


In [167]:
#very closer to 0, it is orthogonal
#because we use the perfect matrix (symmetric matrix)
v1 = evecs[:,0]
v2 = evecs[:,1]

v1 @ v2

5.551115123125783e-17